[package]
name = "kvstore_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic  = "0.12.3"
tokio = { version = "1.32", features = ["full"] }
prost = "0.13.3"

[build-dependencies]
tonic-build = "0.12.3"